### ISSUE TITLE
GitHub+sqlite 部署后，Actions工作流运行时间非常长或者报错

### ISSUE THREAD

**Issue by freedomgod** [Rock-Candy-Tea/hexo-circle-of-friends#120]
我使用GitHub+sqlite方式部署项目，按照文档在vercel上成功部署，地址为 [友链](https://friends.whfree.top/all)，查看工作流运行时间非常长，不清楚是哪里出问题了，

修改的`fc_settings.yaml`配置如下：
```yaml
LINK: [
      { link: "https:whfree.top/friends", theme: "common2"}
#     { link: "https://www.yyyzyyyz.cn/link/", theme: "butterfly" },  # 友链页地址1，修改为你的友链页地址
#     { link: "https://noionion.top/link/", theme: "butterfly" }, # 友链页地址2
#     { link: "https://immmmm.com/about/", theme: "common1" }, # 友链页地址3
#     ...
]

# 配置项友链
# enable：# 是否启用配置项友链 true/false（针对还未适配主题或者有定制需求的用户）
# json_api：通过json格式配置友链，详见：https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=配置项json友链
# list字段填写格式：["name", "link", "avatar","suffix"]，其中：
#       name：必填，友链的名字
#       link：必填，友链主页地址
#       avatar：必填，头像地址
#       suffix：选填，自定义订阅后缀，主要针对不规范的网站订阅后缀，见示例2
SETTINGS_FRIENDS_LINKS: {
    enable: true,
    json_api: "",
    list: [
        # 示例1：
        ["贰猹の小窝", "https://noionion.top/", "https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg"],
        ["Akilarの糖果屋", "https://akilar.top/", "https://akilar.top/images/headimage.png"],
        ["Eurkon", "https://blog.eurkon.com/", "https://npm.elemecdn.com/eurkon-cdn/hexo/images/user/favicon.jpg"],
        # 示例2：使用suffix的配置如下
        # 程序目前自动获取 "atom.xml", "feed/atom", "rss.xml", "rss2.xml", "feed", "index.xml" 这些后缀
        # 如果目标地址的后缀不在其中，就可以在这里添加
        # 比如 https://elizen.me/hello.xml ，填写：
        # ["elizen", "https://elizen.me/", "https://akilar.top/images/headimage.png", "hello.xml"]
    ]
}
```

截图如下：
![github工作流](https://img.whfree.top/github_issue_img/github_actions_option_status.png)

![github actions 报错](https://img.whfree.top/github_issue_img/github_actions_option_error.png)
