### ISSUE TITLE
希望适配 hexo-theme-stellar 主题

### ISSUE THREAD

**Issue by hermitlsr** [Rock-Candy-Tea/hexo-circle-of-friends#18]
stellar 的友链和 volantis 同源，在 1.5 版本是可以通用的，但我目前在配置 4.0 版本时失败了，目前采用 `'CONFIG_FRIENDS_LINKS['list']' `策略配置成功。

stellar 友链也采用 github + friends.yml 的策略
friends.yml 格式如下：

``` 
group:
  title: 
  description: 
  items:
    - title: 
      avatar: 
      url: 
      screenshot:
      keywords: 
      description: 
```

github 格式如下：
```json
{
    "title": "",
    "url": "",
    "avatar": "",
    "screenshot": "",
    "description": "",
    "keywords": ""
}
```

相关链接：
stellar 主题仓库：https://github.com/xaoxuu/hexo-theme-stellar
stellar 友链策略：https://xaoxuu.com/wiki/stellar/tag-plugins/#%E5%8F%8B%E9%93%BE%E6%A0%87%E7%AD%BE
