### ISSUE TITLE
文章友链爬取

### ISSUE THREAD

**Issue by autjuly** [Rock-Candy-Tea/hexo-circle-of-friends#76]
查看了actions，一直有这种问题：我朋友的博客始终爬取不到处于失联状态，他和我一个框架一个主题，不存在有反爬问题...
![image](https://user-images.githubusercontent.com/87848578/201603531-5aa850f5-efb1-4c87-9ab4-592c8d9b9ed0.png)
![image](https://user-images.githubusercontent.com/87848578/201603586-f3d542c4-41cd-45c5-87f7-f20a62b77bae.png)

**Comment by penndu** [comment]
目测未装插件。

**Comment by autjuly** [comment]
> 目测未装插件。

你好，请问要安装什么插件呢？

**Comment by penndu** [comment]
hexo-generator-feed

**Comment by autjuly** [comment]
> hexo-generator-feed

好的 谢谢你 我这就让他去试试，感谢♥

**Comment by penndu** [comment]
如果成功，记得反馈，并关闭此Issue。

**Comment by autjuly** [comment]
> 如果成功，记得反馈，并关闭此Issue。

没成功呢..大大

**Comment by penndu** [comment]
在博客根目录的`_config.yml`文件中添加如下内容：
```
# Extensions
plugins:
    hexo-generator-feed
#Feed Atom
feed:
    type: atom
    path: atom.xml
    limit: 20
```
